#!/usr/bin/python

import sys

program = 'plotGen'
version = '1.0'

#dataFile = sys.argv[1]
templateFile = 'plotfile.plt'


dataFile = input('Enter Data File Name:')

plotFile = dataFile + ".plt"
# openfile and echo contents
print(dataFile)
fIn = open(dataFile, 'rt')
index = 0

for line in fIn:
		index += 1
		if(index == 3): #Green Weight
			gWeight = line.split(",")[1].rstrip()
			print(gWeight)
		if(index == 4): #Origin
			origin = line.rstrip()
			print(origin)
		if(index == 5): #Coffee Name
			coffeeName = line.rstrip()
			print(coffeeName)
		if(index >=7):
			if line.startswith("roast"):
				firstCrack = int(line.split(",")[1])
				print(firstCrack)
			if line.startswith('crack'):
				secondsPastCrack = int(line.split(",")[1])
				print(secondsPastCrack)
			if line.startswith('r_weight'):
				roastedWeight = int(line.split(",")[1])
				print(roastedWeight)
			if line.startswith('cool'):
				coolTime = int(line.split(",")[1])
				xmax = firstCrack + secondsPastCrack + coolTime
				print(xmax)
mloss = '%4.1f%%' % (100*(1.0 - float(roastedWeight)/float(gWeight)))
print(mloss)
tStartCool = firstCrack + secondsPastCrack
		
fIn.close()

fOut = open(plotFile, 'w')
fIn = open(templateFile, 'rt')
fOut.write('#Plotfile Autogenerated by PiRoaster\n')
fOut.writelines([
'coffeeName = ' + '\'' + origin + ' ' + coffeeName + '\'\n',
'firstCrack = ' + str(firstCrack) + '\n',
'startCooling = ' + str(tStartCool) + '\n',
'fileName = ' + '\'' + dataFile + '\'\n',
'secondsPastCrack = ' + str(secondsPastCrack) + '\n',
'beanMass = ' + str(gWeight) + '\n',
'moistureLoss = ' +  '\'' + mloss + '\'\n',
'xmax = ' + str(xmax) + '\n'
])
# Write the body of the plot file (comes from the plot file template)

for line in fIn:
	fOut.write(line.rstrip())
	fOut.write('\n')


fIn.close()
fOut.close()
